### ISSUE TITLE
Can't make it work (2 issues)

### ISSUE THREAD

**Issue by RwbyChan** [fdekeers/poketools#1]
Hi!

I've been trying to get this to work for a couple hours already but I still wasn't able to get it to work.
The first issue that I am facing is that when I connect open the website from my capture card to see the video output in the browser (to see if it's actually working) while running the app, I get the following error:

```
Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( &alsaApi->baseHostApiRep, params, streamDir, &self->pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1904
Expression 'PaAlsaStreamComponent_Initialize( &self->capture, alsaApi, inParams, StreamDirection_In, NULL != callback )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2171
Expression 'PaAlsaStream_Initialize( stream, alsaHostApi, inputParameters, outputParameters, sampleRate, framesPerBuffer, callback, streamFlags, userData )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2839
Traceback (most recent call last):
  File "/home/pi/Downloads/poketools/shiny_reset.py", line 101, in <module>
    is_shiny = record_and_check_shiny(FREQ, SHINY_AUDIO_FILE, REC_DURATION)
  File "/home/pi/Downloads/poketools/shiny_reset.py", line 40, in record_and_check_shiny
    game_recording = atf.record_game_sound(freq, recording_duration)
  File "/home/pi/Downloads/poketools/audio_template_finder.py", line 13, in record_game_sound
    recording = sd.rec(int(duration*freq), samplerate=freq, channels=1)
  File "/usr/local/lib/python3.9/dist-packages/sounddevice.py", line 274, in rec
    ctx.start_stream(InputStream, samplerate, ctx.input_channels,
  File "/usr/local/lib/python3.9/dist-packages/sounddevice.py", line 2576, in start_stream
    self.stream = StreamClass(samplerate=samplerate,
  File "/usr/local/lib/python3.9/dist-packages/sounddevice.py", line 1415, in __init__
    _StreamBase.__init__(self, kind='input', wrap_callback='array',
  File "/usr/local/lib/python3.9/dist-packages/sounddevice.py", line 892, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "/usr/local/lib/python3.9/dist-packages/sounddevice.py", line 2741, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening InputStream: Device unavailable [PaErrorCode -9985]
```

the above error appears after a few seconds, after I see the following (which is the other issue):
my switch has a thing where it checks if the software can be played before it opens the game, when I see the video output from my capture card, I see it being stuck in a low where it tries to open the game, and keeps spamming A, so it closes the popup to check if the game is playable, tries to start the game, closes popup, over and over.

Any fix for either of these?
Thanks in advance! :)

**Comment by fdekeers** [comment]
Hi,

First of all, thank you for using our tool !

For the first error, it seems to come from the fact that you record the Switch at the same time. It can hinder the sound recording. Try using the tool without recording the Switch.

For the second issue, you simply have to modify the macro that launches the game, according to the input sequence necessary to skip the software check. To do that, you can modify the macro RESET_GAME in the `macros.py` file.

Which machine are you using to run the tool ?

**Comment by RwbyChan** [comment]
Hey!

Thanks for your answer! Back when I tried it for the first time I already tried out changing the macros but it acted up strange somehow. I ended up making my own version of it based of your code which seemed to work better for me, but after a long time it would crash but I wasn't sure what caused it...

I have tried your latest version and when changing the macros and adding an extra line in the code (which I also have in my code)
```
capture_device = 2 
sd.default.device = capture_device
```

where the number is the number in front of your capture card from the list you see using the following command:`
```
python3 -m sounddevice
```

I have tried running your latest version and so far with the changes I did, it seemed to work, although at night it crashed once again giving me the following error:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 193, in accepter
    t.start()
  File "/usr/lib/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

For some additional help, this error appeared after logging "Checking presence of shiny..." (after 238 resets)
And for some additional information, the machine I'm running it on is a Raspberry Pi 4

**Comment by fdekeers** [comment]
Okay, the problem here seems to be quite self-explaining: "can't start new thread"
The new thread here is used to exercise the keys while the main thread does the shiny detection. This is needed because, after some observations, it seems that the virtual controller might be disconnected if it is not exercised for several seconds.
For now, I don't know what could be a fix for it, except re-starting the tool when it happens...
But @augustindelecluse is about to improve the way threads are used in the program, so let's wait for his fix ;)
