### ISSUE TITLE
Threads and Formatting

### ISSUE THREAD

**Issue by cdmckinley** [fdekeers/poketools#7]
Hi,

I've been running a branch of the refactored code merged with both my `audio-input-device` and `arceus` branches, and I'm noticing two errors in the command line. I believe they're related to the refactor, rather than my own changes, but I'm not entirely certain.

This is an example of both errors on the first run through:
~~~
Initiating a battle.
Exception in thread Thread-1:
Recording game sound...
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
TypeError: utils.controller.Controller.busy_wait() argument after * must be an iterable, not int
Checking presence of shiny...
No shiny found. Reset n°1.
~~~

I believe the 'thread' error has to do with the threads being created and never closed (if that's the proper terminology). As for the other error, I've set the script to take `REC_DURATION` from each configuration in my `arceus` branch, which may or may not be related. It seems to be related to the `busy_wait` function, on the line 53, where `self.macro(general.BUSY_WAIT.format(int(seconds * 5)))` is called. I'm not sure what the exact problem or fix is though.

If you don't run into this error running your own code, let me know, and I'll see what I can do to to fix my code.

Thank you!

**Comment by fdekeers** [comment]
Hi, thanks for noticing.
The bug was due to the `busy_wait_background` method, which launches a thread to exercise the A button.
The `args` argument given when creating a `Thread` object must be a list of of arguments, but it was a simple int.
It is now fixed.
